#!/bin/bash
echo " install docker on Linux rocky 9"
echo " make by hoatle"
sudo dnf check-update
sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io
sudo systemctl start docker
sudo systemctl enable docker
sudo systemctl status docker
echo "Docker installation successful"
